# Generated by Django 4.2.7 on 2023-11-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('monthly_income', models.PositiveIntegerField()),
                ('house_rent', models.PositiveIntegerField()),
                ('own_a_car', models.BooleanField(default=False)),
            ],
        ),
    ]
